const shoes = [
    {
        id: 1,
        brand: 'Adidas',
        name: 'Adistar',
        description: 'Solid running shoes',
        price: 180,
        stock: 30,
        category: 'Running',
        thumbnail: './assets/images/adistar/adistar.jpg',
        images: [
            './assets/images/adistar/adistar1.jpg',
            './assets/images/adistar/adistar2.jpg',
        ],
    },
    {
        id: 2,
        brand: 'Adidas',
        name: 'Adizero Boston 10',
        description: 'Fast running shoes with a carbon plate',
        price: 200,
        stock: 20,
        category: 'Running',
        thumbnail: './assets/images/adizero/adizero.jpg',
        images: [
            './assets/images/adizero/adizero1.jpg',
            './assets/images/adizero/adizero2.jpg',
        ],
    },
    {
        id: 3,
        brand: 'Adidas',
        name: 'Takumi Sen 8',
        description: 'Light running shoes with a carbon plate',
        price: 220,
        stock: 10,
        category: 'Running',
        thumbnail: './assets/images/takumi/takumi.jpg',
        images: [
            './assets/images/takumi/takumi1.jpg',
            './assets/images/takumi/takumi2.jpg',
        ],
    },
    {
        id: 4,
        brand: 'Nike',
        name: 'Pegasus',
        description: 'Light running shoes with a carbon plate',
        price: 220,
        stock: 10,
        category: 'Running',
        thumbnail: './assets/images/pegasus/pegasus.jpg',
        images: [
            './assets/images/pegasus/pegasus1.jpg',
            './assets/images/pegasus/pegasus2.jpg',
        ],
    },
    {
        id: 5,
        brand: 'Nike',
        name: 'Vaporfly Next',
        description: 'Professional running shoes from Nike',
        price: 210,
        stock: 15,
        category: 'Running',
        thumbnail: './assets/images/vaporfly/vaporfly.jpg',
        images: [
            './assets/images/vaporfly/vaporfly1.jpg',
            './assets/images/vaporfly/vaporfly2.jpg',
        ],
    },
    {
        id: 6,
        brand: 'Adidas',
        name: 'Campus 80',
        description: 'Casual shoes with prime materials',
        price: 110,
        stock: 35,
        category: 'Casual',
        thumbnail: './assets/images/campus/campus.jpg',
        images: [
            './assets/images/campus/campus1.jpg',
            './assets/images/campus/campus2.jpg',
        ],
    },
    {
        id: 7,
        brand: 'Adidas',
        name: 'NMD R1',
        description: 'Stylish and casual shoes from Adidas',
        price: 100,
        stock: 25,
        category: 'Casual',
        thumbnail: './assets/images/nmd/nmd.jpg',
        images: [
            './assets/images/nmd/nmd1.jpg',
            './assets/images/nmd/nmd2.jpg',
        ],
    },
    {
        id: 8,
        brand: 'Puma',
        name: 'Suede Classic',
        description: 'Casual shoes from Puma',
        price: 210,
        stock: 15,
        category: 'Casual',
        thumbnail: './assets/images/suede/suede.jpg',
        images: [
            './assets/images/suede/suede1.jpg',
            './assets/images/suede/suede2.jpg',
        ],
    },
    {
        id: 9,
        brand: 'Nike',
        name: 'Air Force',
        description: 'Modern casual shoes from Nike',
        price: 130,
        stock: 20,
        category: 'Casual',
        thumbnail: './assets/images/force/force.jpg',
        images: [
            './assets/images/force/force1.jpg',
            './assets/images/force/force2.jpg',
        ],
    },
    {
        id: 10,
        brand: 'Nike',
        name: 'Blazer Mid 77',
        description: 'Best-selling casual shoes from Nike',
        price: 150,
        stock: 5,
        category: 'Casual',
        thumbnail: './assets/images/blazer/blazer.jpg',
        images: [
            './assets/images/blazer/blazer1.jpg',
            './assets/images/blazer/blazer2.jpg',
        ],
    },
    {
        id: 11,
        brand: 'Asics',
        name: 'Gel Kayano 27',
        description: 'Soft trail running shoes from Asics',
        price: 200,
        stock: 10,
        category: 'Trail',
        thumbnail: './assets/images/kayano/kayano.jpg',
        images: [
            './assets/images/kayano/kayano1.jpg',
            './assets/images/kayano/kayano2.jpg',
        ],
    },
    {
        id: 12,
        brand: 'Asics',
        name: 'Gel Excite Trail',
        description: 'Premium trail running shoes',
        price: 210,
        stock: 40,
        category: 'Trail',
        thumbnail: './assets/images/excite/excite.jpg',
        images: [
            './assets/images/excite/excite1.jpg',
            './assets/images/excite/excite2.jpg',
        ],
    },
    {
        id: 13,
        brand: 'Adidas',
        name: 'Agravic Flow 2',
        description: 'Soft and colorful trail running shoes from Adidas',
        price: 170,
        stock: 10,
        category: 'Trail',
        thumbnail: './assets/images/agravic/agravic.jpg',
        images: [
            './assets/images/agravic/agravic1.jpg',
            './assets/images/agravic/agravic2.jpg',
        ],
    },
    {
        id: 14,
        brand: 'Adidas',
        name: 'Two Flow',
        description: 'Premium trail running shoes from Adidas',
        price: 180,
        stock: 15,
        category: 'Trail',
        thumbnail: './assets/images/flow/flow.jpg',
        images: [
            './assets/images/flow/flow1.jpg',
            './assets/images/flow/flow2.jpg',
        ],
    },
    {
        id: 15,
        brand: 'Hoka',
        name: 'Speedgoat',
        description:
            'Professional train running shoes for rocky terrains from Hoka',
        price: 160,
        stock: 10,
        category: 'Trail',
        thumbnail: './assets/images/speedgoat/speedgoat.jpg',
        images: [
            './assets/images/speedgoat/speedgoat1.jpg',
            './assets/images/speedgoat/speedgoat2.jpg',
        ],
    },
    {
        id: 16,
        brand: 'Nike',
        name: 'LeBron 20',
        description: 'Professional basketball shoes from Nike',
        price: 200,
        stock: 10,
        category: 'Basketball',
        thumbnail: './assets/images/lebron/lebron.jpg',
        images: [
            './assets/images/lebron/lebron1.jpg',
            './assets/images/lebron/lebron2.jpg',
        ],
    },
    {
        id: 17,
        brand: 'Nike',
        name: 'KD 15',
        description: 'Professional and colorful basketball shoes from Nike',
        price: 190,
        stock: 20,
        category: 'Basketball',
        thumbnail: './assets/images/kd/kd.jpg',
        images: ['./assets/images/kd/kd1.jpg', './assets/images/kd/kd2.jpg'],
    },
    {
        id: 18,
        brand: 'Nike',
        name: 'Air Jordan 1',
        description: 'Iconic basketball shoes from Nike',
        price: 210,
        stock: 5,
        category: 'Basketball',
        thumbnail: './assets/images/jordan/jordan.jpg',
        images: [
            './assets/images/jordan/jordan1.jpg',
            './assets/images/jordan/jordan2.jpg',
        ],
    },
    {
        id: 19,
        brand: 'Puma',
        name: 'Fusion Nitro',
        description: 'Bouncy basketball shoes from Puma',
        price: 160,
        stock: 20,
        category: 'Basketball',
        thumbnail: './assets/images/fusion/fusion.jpg',
        images: [
            './assets/images/fusion/fusion1.jpg',
            './assets/images/fusion/fusion2.jpg',
        ],
    },
    {
        id: 20,
        brand: 'Puma',
        name: 'Court Rider',
        description: 'Soft basketball shoes from Puma',
        price: 140,
        stock: 25,
        category: 'Basketball',
        thumbnail: './assets/images/court/court.jpg',
        images: [
            './assets/images/court/court1.jpg',
            './assets/images/court/court2.jpg',
        ],
    },
    {
        id: 21,
        brand: 'Asics',
        name: 'Blast FF3',
        description: 'Professional volleyball shoes from Asics',
        price: 170,
        stock: 35,
        category: 'Volleyball',
        thumbnail: './assets/images/blast/blast.jpg',
        images: [
            './assets/images/blast/blast1.jpg',
            './assets/images/blast/blast2.jpg',
        ],
    },
    {
        id: 22,
        brand: 'Asics',
        name: 'Gel Rocket 10',
        description: 'Professional and bouncy volleyball shoes from Asics',
        price: 120,
        stock: 15,
        category: 'Volleyball',
        thumbnail: './assets/images/rocket/rocket.jpg',
        images: [
            './assets/images/rocket/rocket1.jpg',
            './assets/images/rocket/rocket2.jpg',
        ],
    },
    {
        id: 23,
        brand: 'Asics',
        name: 'Sky Elite',
        description: 'Professional volleyball shoes from Asics',
        price: 150,
        stock: 20,
        category: 'Volleyball',
        thumbnail: './assets/images/elite/elite.jpg',
        images: [
            './assets/images/elite/elite1.jpg',
            './assets/images/elite/elite2.jpg',
        ],
    },
    {
        id: 24,
        brand: 'Asics',
        name: 'Gel Tactic',
        description: 'Professional and soft volleyball shoes from Asics',
        price: 160,
        stock: 5,
        category: 'Volleyball',
        thumbnail: './assets/images/tactic/tactic.jpg',
        images: [
            './assets/images/tactic/tactic1.jpg',
            './assets/images/tactic/tactic2.jpg',
        ],
    },
    {
        id: 25,
        brand: 'Asics',
        name: 'FurtherUP',
        description: 'Budget volleyball shoes from Asics',
        price: 90,
        stock: 20,
        category: 'Volleyball',
        thumbnail: './assets/images/further/further.jpg',
        images: [
            './assets/images/further/further1.jpg',
            './assets/images/further/further2.jpg',
        ],
    },
];

const test = document.querySelector('.test');
const body = document.querySelector('.body');

shoes.forEach((shoe) => {
    const newImage = document.createElement('img');
    newImage.src = shoe.thumbnail;
    newImage.style.width = '200px';
    newImage.style.width = '200px';
    body.appendChild(newImage);
});

console.log(shoes.products);
